# NumPy

In [1]:
import numpy as np

### Basics

In [2]:
# 1D array
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [3]:
# 2D array
b = np.array([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
b

array([[1., 2., 3.],
       [4., 5., 6.]])

In [4]:
# dimensions
print(f"a: {a.ndim}")
print(f"b: {b.ndim}")

a: 1
b: 2


In [5]:
# shape
print(f"a: {a.shape}")
print(f"b: {b.shape}")

a: (3,)
b: (2, 3)


In [6]:
# type
print(f"a: {a.dtype}")
print(f"b: {b.dtype}")

a: int64
b: float64


In [7]:
# item size
print(f"a: {a.itemsize} bytes")
print(f"b: {b.itemsize} bytes")

a: 8 bytes
b: 8 bytes


In [8]:
# total size
print(f"a: {a.nbytes} bytes")
print(f"b: {b.nbytes} bytes")

a: 24 bytes
b: 48 bytes


### Accessing/changing elements/rows/columns

In [9]:
a = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [10]:
# specific element [r, c]
print(a[1, 5]) # row 2, column 6
print(a[0, -2]) # row 1, 2nd last column

13
6


In [11]:
# specific row
print(a[0, :]) # first row
print(a[1, :]) # second row

[1 2 3 4 5 6 7]
[ 8  9 10 11 12 13 14]


In [12]:
# specific column
print(a[:, 2]) # third column
print(a[:, -1]) # last column

[ 3 10]
[ 7 14]


In [13]:
# [start:end:step]
a[0, 1:6:2] # row 1, columns 2 to 6, step 2

array([2, 4, 6])

In [14]:
# changing element
a[1, 5] = 20
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 20, 14]])

In [15]:
# changing row
a[0, :] = 100
a

array([[100, 100, 100, 100, 100, 100, 100],
       [  8,   9,  10,  11,  12,  20,  14]])

In [16]:
# changing column
a[:, 2] = 50
a

array([[100, 100,  50, 100, 100, 100, 100],
       [  8,   9,  50,  11,  12,  20,  14]])

#### 3D array

In [17]:
b = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [18]:
# specific element - outside in
b[0, 1, 1]

np.int64(4)

In [19]:
# specific row
b[1, 0, :]

array([5, 6])

In [20]:
# specific column
b[0, :, 0]

array([1, 3])

In [21]:
# replace
b[:, 1, :] = [[9, 9], [8, 8]]
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

### Different types of arrays

In [22]:
# all zeros
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
# all ones
np.ones((4, 2, 2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [24]:
# any number
np.full((2, 2), 99)

array([[99, 99],
       [99, 99]])

In [25]:
# full_like
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [26]:
# random decimal numbers
np.random.rand(4, 2)

array([[0.96163454, 0.84082594],
       [0.99451521, 0.50743784],
       [0.08899805, 0.19049978],
       [0.84068375, 0.59028186]])

In [27]:
# passing a shape
np.random.random_sample(a.shape)

array([[0.76697696, 0.04805715, 0.40097045, 0.0826735 , 0.87404123,
        0.95634596, 0.10026386],
       [0.21634457, 0.96736204, 0.32342806, 0.97883539, 0.82383583,
        0.44129949, 0.95528455]])

In [28]:
# random integers
np.random.randint(7, size=(3, 3))

array([[1, 0, 2],
       [2, 2, 5],
       [2, 5, 5]])

In [29]:
# identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [30]:
# repeating arrays
arr = np.array([[1, 2, 3]])
r1 = np.repeat(arr, 3, axis=0)
r1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [31]:
output = np.ones((5, 5))
output

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [32]:
z = np.zeros((3, 3))
z[1, 1] = 9
z

array([[0., 0., 0.],
       [0., 9., 0.],
       [0., 0., 0.]])

In [33]:
output[1:-1, 1:-1] = z
output

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [34]:
# copying arrays
a = np.array([1, 2, 3])
b = a.copy()
b[0] = 100
print(a)
print(b)

[1 2 3]
[100   2   3]


### Mathematics

In [35]:
a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

In [36]:
a + 2

array([3, 4, 5, 6])

In [37]:
a - 2

array([-1,  0,  1,  2])

In [38]:
a * 2

array([2, 4, 6, 8])

In [39]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [40]:
b = np.array([0, 1, 1, 0])
a + b

array([1, 3, 4, 4])

In [41]:
a ** 2

array([ 1,  4,  9, 16])

In [42]:
# trigonometric functions
print(f"sin: {np.sin(a)}")
print(f"cos: {np.cos(a)}")
print(f"tan: {np.tan(a)}")

sin: [ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
cos: [ 0.54030231 -0.41614684 -0.9899925  -0.65364362]
tan: [ 1.55740772 -2.18503986 -0.14254654  1.15782128]


#### Linear algebra

In [43]:
a = np.ones((2, 3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [44]:
b = np.full((3, 2), 2)
b

array([[2, 2],
       [2, 2],
       [2, 2]])

In [45]:
np.matmul(a, b)

array([[6., 6.],
       [6., 6.]])

In [46]:
c = np.identity(3)
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [47]:
np.linalg.det(c)

np.float64(1.0)

#### Statistics

In [48]:
stats = np.array([[1, 2, 3], [4, 5, 6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [49]:
np.min(stats)

np.int64(1)

In [50]:
np.max(stats)

np.int64(6)

In [51]:
np.min(stats, axis=0)

array([1, 2, 3])

In [52]:
np.sum(stats, axis=1)

array([ 6, 15])

### Reorganizing arrays

In [53]:
before = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
before

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [54]:
before.shape

(2, 4)

In [55]:
after = before.reshape((2, 2, 2))
after

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [56]:
# vertically stacking vectors
v1 = np.array([1, 2, 3, 4])
v2 = np.array([5, 6, 7, 8])
np.vstack((v1, v2))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [57]:
# horizontally stacking vectors
np.hstack((v1, v2))

array([1, 2, 3, 4, 5, 6, 7, 8])